/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as DemandesIndexRouteImport } from './routes/demandes/index'
import { Route as DemandesIdRouteImport } from './routes/demandes/$id'
import { Route as InterneFacilitationRouteImport } from './routes/interne/facilitation'
import { Route as InterneFinanceRouteImport } from './routes/interne/finance'
import { Route as InterneImportsRouteImport } from './routes/interne/imports'
import { Route as InterneVerificationRouteImport } from './routes/interne/verification'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIndexRoute = DemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdRoute = DemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneFacilitationRoute = InterneFacilitationRouteImport.update({
  id: '/interne/facilitation',
  path: '/interne/facilitation',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneFinanceRoute = InterneFinanceRouteImport.update({
  id: '/interne/finance',
  path: '/interne/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneImportsRoute = InterneImportsRouteImport.update({
  id: '/interne/imports',
  path: '/interne/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneVerificationRoute = InterneVerificationRouteImport.update({
  id: '/interne/verification',
  path: '/interne/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/documents': typeof DocumentsRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partenaires': typeof PartenairesRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/interne/facilitation': typeof InterneFacilitationRoute
  '/interne/finance': typeof InterneFinanceRoute
  '/interne/imports': typeof InterneImportsRoute
  '/interne/verification': typeof InterneVerificationRoute
  '/demandes/': typeof DemandesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/documents': typeof DocumentsRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partenaires': typeof PartenairesRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/interne/facilitation': typeof InterneFacilitationRoute
  '/interne/finance': typeof InterneFinanceRoute
  '/interne/imports': typeof InterneImportsRoute
  '/interne/verification': typeof InterneVerificationRoute
  '/demandes': typeof DemandesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/documents': typeof DocumentsRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/parametres': typeof ParametresRoute
  '/partenaires': typeof PartenairesRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/interne/facilitation': typeof InterneFacilitationRoute
  '/interne/finance': typeof InterneFinanceRoute
  '/interne/imports': typeof InterneImportsRoute
  '/interne/verification': typeof InterneVerificationRoute
  '/demandes/': typeof DemandesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/documents'
    | '/fournisseurs'
    | '/login'
    | '/parametres'
    | '/partenaires'
    | '/signup'
    | '/transactions'
    | '/api/upload'
    | '/demandes/$id'
    | '/interne/facilitation'
    | '/interne/finance'
    | '/interne/imports'
    | '/interne/verification'
    | '/demandes/'
    | '/api/auth/$'
    | '/api/files/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/documents'
    | '/fournisseurs'
    | '/login'
    | '/parametres'
    | '/partenaires'
    | '/signup'
    | '/transactions'
    | '/api/upload'
    | '/demandes/$id'
    | '/interne/facilitation'
    | '/interne/finance'
    | '/interne/imports'
    | '/interne/verification'
    | '/demandes'
    | '/api/auth/$'
    | '/api/files/$id'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/documents'
    | '/fournisseurs'
    | '/login'
    | '/parametres'
    | '/partenaires'
    | '/signup'
    | '/transactions'
    | '/api/upload'
    | '/demandes/$id'
    | '/interne/facilitation'
    | '/interne/finance'
    | '/interne/imports'
    | '/interne/verification'
    | '/demandes/'
    | '/api/auth/$'
    | '/api/files/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  DocumentsRoute: typeof DocumentsRoute
  FournisseursRoute: typeof FournisseursRoute
  LoginRoute: typeof LoginRoute
  ParametresRoute: typeof ParametresRoute
  PartenairesRoute: typeof PartenairesRoute
  SignupRoute: typeof SignupRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  DemandesIdRoute: typeof DemandesIdRoute
  InterneFacilitationRoute: typeof InterneFacilitationRoute
  InterneFinanceRoute: typeof InterneFinanceRoute
  InterneImportsRoute: typeof InterneImportsRoute
  InterneVerificationRoute: typeof InterneVerificationRoute
  DemandesIndexRoute: typeof DemandesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/': {
      id: '/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof DemandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id': {
      id: '/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof DemandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/facilitation': {
      id: '/interne/facilitation'
      path: '/interne/facilitation'
      fullPath: '/interne/facilitation'
      preLoaderRoute: typeof InterneFacilitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/finance': {
      id: '/interne/finance'
      path: '/interne/finance'
      fullPath: '/interne/finance'
      preLoaderRoute: typeof InterneFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/imports': {
      id: '/interne/imports'
      path: '/interne/imports'
      fullPath: '/interne/imports'
      preLoaderRoute: typeof InterneImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/verification': {
      id: '/interne/verification'
      path: '/interne/verification'
      fullPath: '/interne/verification'
      preLoaderRoute: typeof InterneVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  DocumentsRoute: DocumentsRoute,
  FournisseursRoute: FournisseursRoute,
  LoginRoute: LoginRoute,
  ParametresRoute: ParametresRoute,
  PartenairesRoute: PartenairesRoute,
  SignupRoute: SignupRoute,
  TransactionsRoute: TransactionsRoute,
  ApiUploadRoute: ApiUploadRoute,
  DemandesIdRoute: DemandesIdRoute,
  InterneFacilitationRoute: InterneFacilitationRoute,
  InterneFinanceRoute: InterneFinanceRoute,
  InterneImportsRoute: InterneImportsRoute,
  InterneVerificationRoute: InterneVerificationRoute,
  DemandesIndexRoute: DemandesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
