/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ReinitialiserRouteImport } from './routes/reinitialiser'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ApiSourceUploadRouteImport } from './routes/api/source-upload'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as DemandesIndexRouteImport } from './routes/demandes/index'
import { Route as DemandesIdRouteImport } from './routes/demandes/$id'
import { Route as InterneClientsRouteImport } from './routes/interne/clients'
import { Route as InterneFacilitationRouteImport } from './routes/interne/facilitation'
import { Route as InterneFinanceRouteImport } from './routes/interne/finance'
import { Route as InternePlansRouteImport } from './routes/interne/plans'
import { Route as InterneSourcesRouteImport } from './routes/interne/sources'
import { Route as InterneUtilisateursRouteImport } from './routes/interne/utilisateurs'
import { Route as InterneVerificationRouteImport } from './routes/interne/verification'
import { Route as InvitationIdRouteImport } from './routes/invitation.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'
import { Route as DemandesIdRapportRouteImport } from './routes/demandes/$id.rapport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserRoute = ReinitialiserRouteImport.update({
  id: '/reinitialiser',
  path: '/reinitialiser',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceUploadRoute = ApiSourceUploadRouteImport.update({
  id: '/api/source-upload',
  path: '/api/source-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIndexRoute = DemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdRoute = DemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneClientsRoute = InterneClientsRouteImport.update({
  id: '/interne/clients',
  path: '/interne/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneFacilitationRoute = InterneFacilitationRouteImport.update({
  id: '/interne/facilitation',
  path: '/interne/facilitation',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneFinanceRoute = InterneFinanceRouteImport.update({
  id: '/interne/finance',
  path: '/interne/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InternePlansRoute = InternePlansRouteImport.update({
  id: '/interne/plans',
  path: '/interne/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneSourcesRoute = InterneSourcesRouteImport.update({
  id: '/interne/sources',
  path: '/interne/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneUtilisateursRoute = InterneUtilisateursRouteImport.update({
  id: '/interne/utilisateurs',
  path: '/interne/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterneVerificationRoute = InterneVerificationRouteImport.update({
  id: '/interne/verification',
  path: '/interne/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdRapportRoute = DemandesIdRapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => DemandesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/documents': typeof DocumentsRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/parametres': typeof ParametresRoute
  '/reinitialiser': typeof ReinitialiserRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/api/source-upload': typeof ApiSourceUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/demandes/$id': typeof DemandesIdRouteWithChildren
  '/interne/clients': typeof InterneClientsRoute
  '/interne/facilitation': typeof InterneFacilitationRoute
  '/interne/finance': typeof InterneFinanceRoute
  '/interne/plans': typeof InternePlansRoute
  '/interne/sources': typeof InterneSourcesRoute
  '/interne/utilisateurs': typeof InterneUtilisateursRoute
  '/interne/verification': typeof InterneVerificationRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/demandes/': typeof DemandesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/demandes/$id/rapport': typeof DemandesIdRapportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/documents': typeof DocumentsRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/parametres': typeof ParametresRoute
  '/reinitialiser': typeof ReinitialiserRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/api/source-upload': typeof ApiSourceUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/demandes/$id': typeof DemandesIdRouteWithChildren
  '/interne/clients': typeof InterneClientsRoute
  '/interne/facilitation': typeof InterneFacilitationRoute
  '/interne/finance': typeof InterneFinanceRoute
  '/interne/plans': typeof InternePlansRoute
  '/interne/sources': typeof InterneSourcesRoute
  '/interne/utilisateurs': typeof InterneUtilisateursRoute
  '/interne/verification': typeof InterneVerificationRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/demandes': typeof DemandesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/demandes/$id/rapport': typeof DemandesIdRapportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses': typeof AnalysesRoute
  '/documents': typeof DocumentsRoute
  '/fournisseurs': typeof FournisseursRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/parametres': typeof ParametresRoute
  '/reinitialiser': typeof ReinitialiserRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/api/source-upload': typeof ApiSourceUploadRoute
  '/api/upload': typeof ApiUploadRoute
  '/demandes/$id': typeof DemandesIdRouteWithChildren
  '/interne/clients': typeof InterneClientsRoute
  '/interne/facilitation': typeof InterneFacilitationRoute
  '/interne/finance': typeof InterneFinanceRoute
  '/interne/plans': typeof InternePlansRoute
  '/interne/sources': typeof InterneSourcesRoute
  '/interne/utilisateurs': typeof InterneUtilisateursRoute
  '/interne/verification': typeof InterneVerificationRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/demandes/': typeof DemandesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/demandes/$id/rapport': typeof DemandesIdRapportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses'
    | '/documents'
    | '/fournisseurs'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/parametres'
    | '/reinitialiser'
    | '/signup'
    | '/transactions'
    | '/api/source-upload'
    | '/api/upload'
    | '/demandes/$id'
    | '/interne/clients'
    | '/interne/facilitation'
    | '/interne/finance'
    | '/interne/plans'
    | '/interne/sources'
    | '/interne/utilisateurs'
    | '/interne/verification'
    | '/invitation/$id'
    | '/demandes/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/demandes/$id/rapport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses'
    | '/documents'
    | '/fournisseurs'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/parametres'
    | '/reinitialiser'
    | '/signup'
    | '/transactions'
    | '/api/source-upload'
    | '/api/upload'
    | '/demandes/$id'
    | '/interne/clients'
    | '/interne/facilitation'
    | '/interne/finance'
    | '/interne/plans'
    | '/interne/sources'
    | '/interne/utilisateurs'
    | '/interne/verification'
    | '/invitation/$id'
    | '/demandes'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/demandes/$id/rapport'
  id:
    | '__root__'
    | '/'
    | '/analyses'
    | '/documents'
    | '/fournisseurs'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/parametres'
    | '/reinitialiser'
    | '/signup'
    | '/transactions'
    | '/api/source-upload'
    | '/api/upload'
    | '/demandes/$id'
    | '/interne/clients'
    | '/interne/facilitation'
    | '/interne/finance'
    | '/interne/plans'
    | '/interne/sources'
    | '/interne/utilisateurs'
    | '/interne/verification'
    | '/invitation/$id'
    | '/demandes/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/demandes/$id/rapport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesRoute: typeof AnalysesRoute
  DocumentsRoute: typeof DocumentsRoute
  FournisseursRoute: typeof FournisseursRoute
  LoginRoute: typeof LoginRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ParametresRoute: typeof ParametresRoute
  ReinitialiserRoute: typeof ReinitialiserRoute
  SignupRoute: typeof SignupRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiSourceUploadRoute: typeof ApiSourceUploadRoute
  ApiUploadRoute: typeof ApiUploadRoute
  DemandesIdRoute: typeof DemandesIdRouteWithChildren
  InterneClientsRoute: typeof InterneClientsRoute
  InterneFacilitationRoute: typeof InterneFacilitationRoute
  InterneFinanceRoute: typeof InterneFinanceRoute
  InternePlansRoute: typeof InternePlansRoute
  InterneSourcesRoute: typeof InterneSourcesRoute
  InterneUtilisateursRoute: typeof InterneUtilisateursRoute
  InterneVerificationRoute: typeof InterneVerificationRoute
  InvitationIdRoute: typeof InvitationIdRoute
  DemandesIndexRoute: typeof DemandesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser': {
      id: '/reinitialiser'
      path: '/reinitialiser'
      fullPath: '/reinitialiser'
      preLoaderRoute: typeof ReinitialiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source-upload': {
      id: '/api/source-upload'
      path: '/api/source-upload'
      fullPath: '/api/source-upload'
      preLoaderRoute: typeof ApiSourceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/': {
      id: '/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof DemandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id': {
      id: '/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof DemandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/clients': {
      id: '/interne/clients'
      path: '/interne/clients'
      fullPath: '/interne/clients'
      preLoaderRoute: typeof InterneClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/facilitation': {
      id: '/interne/facilitation'
      path: '/interne/facilitation'
      fullPath: '/interne/facilitation'
      preLoaderRoute: typeof InterneFacilitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/finance': {
      id: '/interne/finance'
      path: '/interne/finance'
      fullPath: '/interne/finance'
      preLoaderRoute: typeof InterneFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/plans': {
      id: '/interne/plans'
      path: '/interne/plans'
      fullPath: '/interne/plans'
      preLoaderRoute: typeof InternePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/sources': {
      id: '/interne/sources'
      path: '/interne/sources'
      fullPath: '/interne/sources'
      preLoaderRoute: typeof InterneSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/utilisateurs': {
      id: '/interne/utilisateurs'
      path: '/interne/utilisateurs'
      fullPath: '/interne/utilisateurs'
      preLoaderRoute: typeof InterneUtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interne/verification': {
      id: '/interne/verification'
      path: '/interne/verification'
      fullPath: '/interne/verification'
      preLoaderRoute: typeof InterneVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id/rapport': {
      id: '/demandes/$id/rapport'
      path: '/rapport'
      fullPath: '/demandes/$id/rapport'
      preLoaderRoute: typeof DemandesIdRapportRouteImport
      parentRoute: typeof DemandesIdRoute
    }
  }
}

interface DemandesIdRouteChildren {
  DemandesIdRapportRoute: typeof DemandesIdRapportRoute
}

const DemandesIdRouteChildren: DemandesIdRouteChildren = {
  DemandesIdRapportRoute: DemandesIdRapportRoute,
}

const DemandesIdRouteWithChildren = DemandesIdRoute._addFileChildren(
  DemandesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesRoute: AnalysesRoute,
  DocumentsRoute: DocumentsRoute,
  FournisseursRoute: FournisseursRoute,
  LoginRoute: LoginRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ParametresRoute: ParametresRoute,
  ReinitialiserRoute: ReinitialiserRoute,
  SignupRoute: SignupRoute,
  TransactionsRoute: TransactionsRoute,
  ApiSourceUploadRoute: ApiSourceUploadRoute,
  ApiUploadRoute: ApiUploadRoute,
  DemandesIdRoute: DemandesIdRouteWithChildren,
  InterneClientsRoute: InterneClientsRoute,
  InterneFacilitationRoute: InterneFacilitationRoute,
  InterneFinanceRoute: InterneFinanceRoute,
  InternePlansRoute: InternePlansRoute,
  InterneSourcesRoute: InterneSourcesRoute,
  InterneUtilisateursRoute: InterneUtilisateursRoute,
  InterneVerificationRoute: InterneVerificationRoute,
  InvitationIdRoute: InvitationIdRoute,
  DemandesIndexRoute: DemandesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
